swagger: 2.0

info:  title: US Core  Server
  description: This profile defines the expected capabilities of the US Core Server conforming to the US Core IG.
  version: 1.0.1
  # contact:
    # end user to fill out
  license:
    name: null

# host: [user to provide]
# basePath: [user to provide]
schemes:
  - https
  # - http this would not normally be allowed (see doco)
consumes:
produces:
